name: 'Factorio mod portal upload'
description: 'Upload your mod to the specified Factorio Mod Portal modpage'
author: 'lisekilis'
inputs:
  info-path:
    description: 'Location of info.json'
    default: 'src/info.json'
  mod-dir:
    description: 'Directory containing the the mod archive'
    default: 'dist'
outputs:
  url:
    description: 'url of the uploaded mod'
runs:
  using: node20
  main: dist/index.js
branding:
  icon: upload
  color: orange
