name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        id: setup-pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'pnpm'

      - name: Install Dependencies
        id: pnpm-i
        run: pnpm i

      - name: Check Format
        id: pnpm-format-check
        run: pnpm run format:check

      - name: Lint
        id: pnpm-lint
        run: pnpm lint

      - name: Test
        id: pnpm-ci-test
        run: pnpm ci-test --passWithNoTests

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        env: 
          FACTORIO_API_TOKEN: ${{ secrets.FACTORIO_UPLOAD_TOKEN }}

          

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
